### ISSUE TITLE
Add docs for queries that take parameters.

### ISSUE THREAD

**Issue by luc-tielen** [ollef/rock#1]
Hello, I integrated `rock` in my [eclair compiler](https://github.com/luc-tielen/eclair-lang). You can find the relevant code [here](https://github.com/luc-tielen/eclair-lang/blob/main/lib/Eclair.hs).

Overall it was a really smooth integration and really cleaned up a lot of code, so kudos!
One thing that was not as clear straight away, was that it's possible that queries can take arguments to further parametrize the task in the `rules`. 

Feel free to use some of the code for extra documentation examples if you want.

EDIT: another question: is it normal that all my queries return an IO action (or potentially some other application monad)? Maybe also good to add docs for this situation?

**Comment by ollef** [comment]
Thanks a lot for the feedback! I'll see if I can incorporate it next time I do some work on Rock. If you'd like to contribute it in the meantime (add links to your project, mention query parameters, etc) you'd be welcome to do so and I'd also be happy to hand out commit bits.

About IO: Since any task that fetches queries needs to be a Task, which has IO capabilities, I'd say it's currently normal. It's questionable whether it's good though, because it might e.g. lead to someone making non-deterministic queries if they're careless. But for my use-case (and with the discipline of mostly one-person projects) I've found it convenient if not just to be able to do logging anywhere. Maybe the right way to go is to parameterize tasks by the base monad to not force IO on everybody. What do you think?

**Comment by luc-tielen** [comment]
I will make a small docs PR somewhere this week for some things that weren't clear to me. :smile:

Your response about IO made me look at my code again, my queries also had a tag of `IO ...` while this is not needed. I guess this is something that could be mentioned in docs as well. (Since I think it would build up the IO actions in parallel and then evaluate it at the end sequentially?)

For me running in just IO is fine, since the "outer layers" of the compiler need to do IO anyway. But if you needed a custom monad stack, then maybe you would need to change the `Task` type (probably easiest by adding a transformer `t` that adds additional effects to the `ReaderT ... IO`?). But like I said, I don't need this right now so maybe best to just keep it simple for now!
